spring.application.name=ecommerce

spring.config.import=optional:file:.env[.properties]

# Database Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?user=postgres.wfkxqdiqfxmmcpjyjkfw&password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Configurations
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.format_sql = true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

# Stripe API Keys
stripe.api.key=${STRIPE_SECRET}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET}

# Stripe redirected URL
stripe.success-url=http://localhost:8080/api/v1/payments/success?session_id={CHECKOUT_SESSION_ID}
stripe.cancel-url=http://localhost:8080/api/v1/payments/cancel}